import{a as w,S as v,i}from"./assets/vendor-C3lJ7lpQ.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&r(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function r(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const q="https://pixabay.com/api/",E="51776456-27ec020609b15dc1d566099b7";async function f(t,n=1,s=15){const r={key:E,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:n,per_page:s};return(await w.get(q,{params:r})).data}const u=document.querySelector(".gallery");document.querySelector(".loader");document.querySelector(".load-more");let M=new v(".gallery a",{captionsData:"alt",captionDelay:250});function p(t,n=!1){const s=t.map(({webformatURL:r,largeImageURL:e,tags:o,likes:a,views:L,comments:b,downloads:S})=>`
    <a href="${e}" class="gallery-item">
      <div class="photo-card">
        <img src="${r}" alt="${o}" loading="lazy" />
        <div class="info">
          <p><b>Likes:</b> ${a}</p>
          <p><b>Views:</b> ${L}</p>
          <p><b>Comments:</b> ${b}</p>
          <p><b>Downloads:</b> ${S}</p>
        </div>
      </div>
    </a>`).join("");n?u.insertAdjacentHTML("beforeend",s):u.innerHTML=s,M.refresh()}function P(){u.innerHTML=""}function g(){document.querySelector(".loader").classList.remove("hidden")}function l(){document.querySelector(".loader").classList.add("hidden")}function h(){document.querySelector(".load-more").classList.remove("hidden")}function y(){document.querySelector(".load-more").classList.add("hidden")}let m="",c=1;const d=15,R=document.querySelector("#search-form"),I=document.querySelector(".load-more");R.addEventListener("submit",$);I.addEventListener("click",B);async function $(t){t.preventDefault();const s=t.currentTarget.elements.searchQuery.value.trim();if(!s){i.error({title:"Error",message:"Please enter a search term!",position:"topRight"});return}m=s,c=1,P(),y(),g();try{const r=await f(m,c,d);if(!r||!r.hits){i.error({title:"Error",message:"Invalid API response",position:"topRight"}),l();return}if(r.hits.length===0){i.warning({title:"No results",message:"Sorry, no images found. Try another search!",position:"topRight"}),l();return}p(r.hits),r.totalHits>d&&h()}catch{i.error({title:"Error",message:"Something went wrong while fetching data.",position:"topRight"})}finally{l()}}async function B(){c+=1,y(),g();try{const t=await f(m,c,d);p(t.hits,!0);const n=Math.ceil(t.totalHits/d);c<n?h():i.info({title:"End of results",message:"You have reached the end of search results.",position:"topRight"}),H()}catch{i.error({title:"Error",message:"Failed to load more images.",position:"topRight"}),h()}finally{l()}}function H(){const{height:t}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
