import{a as w,S as B,i}from"./assets/vendor-C3lJ7lpQ.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))t(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&t(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function t(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const v="https://pixabay.com/api/",q="51776456-27ec020609b15dc1d566099b7";async function h(o,n=1,s=15){const t={key:q,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:n,per_page:s};return(await w.get(v,{params:t})).data}const d=document.querySelector(".gallery");document.querySelector(".loader");document.querySelector(".load-more");let D=new B(".gallery a",{captionsData:"alt",captionDelay:250});function m(o,n=!1){const s=o.map(({webformatURL:t,largeImageURL:e,tags:r,likes:a,views:S,comments:b,downloads:R})=>`
    <a href="${e}" class="gallery-item">
      <div class="photo-card">
        <img src="${t}" alt="${r}" loading="lazy" />
        <div class="info">
          <p><b>Likes:</b> ${a}</p>
          <p><b>Views:</b> ${S}</p>
          <p><b>Comments:</b> ${b}</p>
          <p><b>Downloads:</b> ${R}</p>
        </div>
      </div>
    </a>`).join("");n?d.insertAdjacentHTML("beforeend",s):d.innerHTML=s,D.refresh()}function M(){d.innerHTML=""}function f(){document.querySelector(".loader").classList.remove("hidden")}function g(){document.querySelector(".loader").classList.add("hidden")}function p(){document.querySelector(".load-more").classList.remove("hidden")}function y(){document.querySelector(".load-more").classList.add("hidden")}let u="",c=1;const l=15,L=document.querySelector("#search-form"),E=document.querySelector(".load-more");console.log("DEBUG: searchForm =",L);console.log("DEBUG: loadMoreBtn =",E);L.addEventListener("submit",G);E.addEventListener("click",O);async function G(o){o.preventDefault(),console.log("DEBUG: onSearch triggered ✅"),console.log("DEBUG: event.currentTarget.elements =",o.currentTarget.elements);const n=o.currentTarget.elements.searchQuery;if(!n){console.error("❌ ERROR: searchQuery input not found у формі");return}const s=n.value.trim();if(console.log("DEBUG: searchValue =",s),!s){i.error({title:"Error",message:"Please enter a search term!",position:"topRight"});return}u=s,c=1,M(),y(),f();try{const t=await h(u,c,l);if(console.log("DEBUG: fetchImages response =",t),!t||!t.hits){console.error("❌ ERROR: API response is invalid");return}if(t.hits.length===0){i.warning({title:"No results",message:"Sorry, no images found. Try another search!",position:"topRight"});return}m(t.hits),t.totalHits>l&&p()}catch(t){console.error("❌ ERROR in onSearch:",t),i.error({title:"Error",message:"Something went wrong while fetching data.",position:"topRight"})}finally{g()}}async function O(){console.log("DEBUG: onLoadMore triggered ✅"),c+=1,y(),f();try{const o=await h(u,c,l);console.log("DEBUG: fetchImages response (load more) =",o),m(o.hits,!0);const n=Math.ceil(o.totalHits/l);c<n?p():i.info({title:"End of results",message:"You have reached the end of search results.",position:"topRight"}),P()}catch(o){console.error("❌ ERROR in onLoadMore:",o),i.error({title:"Error",message:"Failed to load more images.",position:"topRight"})}finally{g()}}function P(){const{height:o}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
